[project]
version = "0.0.1"
name = "investory"
dependencies = [
  "pandas",
  "matplotlib",
  "yahooquery",
  "plotext"]

[tool.setuptools]
packages = ["investory"]

[tool.pyright]
venvPath = "/home/nasser/.venvs/"
venv = "general"
typeCheckingMode = "basic"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F", "W"]
ignore = [
  # "E501"                        # line lentgh
]
preview = true
