[project]
version = "0.0.1"
name = "investory"
dependencies = ["pandas", "yahooquery"]

[tool.flake8]
max-line-length = 88            # same as black

# language server also use pycodestyle
[tool.pycodestyle]
max-line-length = 120

[tool.pyright]
venvPath = "/home/nasser/.venv/"
venv = "general"