* Introduction

Simple collection of module and function based on Python Pandas to manage an investment portfolio treated as an inventory of items.

* Features
* Installing

Create a virtual environment, if it already does not exist[fn:1].

#+begin_src sh
python -m venv ~/.venv/general
#+end_src

Then using pip from the virtual environment on the source code root directory.
The flag =-e= is for "editable" so one can edit the source code.

#+begin_src sh :results silent
cd ~/.local/src/investory/
~/.venv/general/bin/pip install -e . 
#+end_src

[fn:1] https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-virtual-environments 

* How to use it
:PROPERTIES:
:header-args: :exports both
:END:
** Values module
*** Stock split value

Considering split, this stock split on 2019-09-25 in the proportion 1:3.
This means, that each sock turns into 3.
In 2023-01-25 it split in the proportion 30:1.
Every 30 stock is converted to 1.

The historical price of the asset should be adjusted for the split.
In 2019-08-30, the price was 82.33.
In the following month the stock split into three, so the price should be reduced by the same factor.
The closing price on the next month 2019-09-30 is 28.57. 

#+begin_src sh :dir examples/values/ :results silent
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity IRBR3 --split 30:1,2023-01-25 1:3,2019-09-26"
pueue clean
#+end_src

*** Specify currency from commodity

Specify currency:

#+begin_src sh :dir examples/values/ :results silent
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity ^BVSP --begin 2023-01-01 --currency R$"
pueue clean
#+end_src

#+RESULTS:
#+begin_example
P 2023-01-31 "^BVSP" R$113532.000000
P 2023-02-28 "^BVSP" R$104932.000000
P 2023-03-31 "^BVSP" R$101882.000000
P 2023-04-28 "^BVSP" R$104432.000000
P 2023-05-31 "^BVSP" R$108335.000000
P 2023-06-30 "^BVSP" R$118087.000000
P 2023-07-31 "^BVSP" R$121943.000000
P 2023-08-31 "^BVSP" R$115742.000000
P 2023-09-29 "^BVSP" R$116565.000000
P 2023-10-31 "^BVSP" R$113144.000000
#+end_example

*** Specify different commodity name from Yahoo

With different yahoo ticker than the commodity symbol.
For example we can use € in the ledger but yahoo identifies it as "EURUSD=X".
Or we can use BTC in our ledger but at Yahoo they use "BTC-USD".

#+begin_src sh :dir examples/values/ :results silent
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity € --yahooticker eurusd=x --begin 2023-01-01"
pueue clean
#+end_src

#+begin_src sh :dir examples/values/ :results silent
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity BTC --yahooticker BTC-USD --begin 2023-01-01"
pueue clean
#+end_src

*** Get only the latest price to the ledger

Usual functionality, get only the latest day for each month.

#+begin_src sh :dir examples/values/ :results silent
date
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity VWCE --yahooticker VWCE.DE --begin 2024-08-01"
pueue clean
#+end_src

#+begin_src sh :dir examples/values/
head VWCE.DE.ledger
rm -rf VWCE.DE.ledger
#+end_src

#+RESULTS:
: P 2024-08-30 "VWCE" $123.019997
: P 2024-09-30 "VWCE" $125.199997

However, today is 2024-02-03 and we want to check the current value of our holdings.

#+begin_src sh :dir examples/values/ :results silent
date
python=~/.venv/general/bin/python
pueue add "$python -m investory.values --commodity VWCE --yahooticker VWCE.DE --begin 2024-01-01 --latest-price"
#+end_src

#+begin_src sh :dir examples/values/
cat VWCE.DE.ledger
rm -rf VWCE.DE.ledger
#+end_src

#+RESULTS:
: Sa 03 Feb 2024 08:50:34 CET
: P 2024-01-31 "VWCE" $110.139999
: P 2024-02-02 "VWCE" $111.339996

** Cost basis module

See tests.

** Reports

Consider a simple ledger involving investments:

#+begin_src ledger :tangle examples/reports/all.ledger
2021-03-26 * buy VWCE
    assets:investments:etf:VWCE    10.0 VWCE @ € 100
    assets:brokerage

2021-03-26 * buy AAPL
    assets:investments:stocks:AAPL    10.0 AAPL @ € 200
    assets:brokerage

2021-03-26 * buy BTC
    assets:investments:crypto:BTC    1 BTC @ € 1000
    assets:brokerage
    
2022-04-17 * buy VWCE
    assets:investments:etf:VWCE    10.0 VWCE @ € 200
    assets:brokerage

2022-03-26 * buy AAPL
    assets:investments:stocks:AAPL    10.0 AAPL @ € 300
    assets:brokerage

2021-12-26 * sell BTC
    assets:investments:crypto:BTC    -1 BTC @ € 10000
    assets:brokerage
#+end_src

Reports are generated with the command:

#+begin_src sh :dir examples/reports/ :results silent
python=~/.venv/general/bin/python
$python -m investory.reports
#+end_src

It generates a report for each year, and a summary with current position.

[[file:examples/reports/reports/asset-evolution.svg]] [[file:examples/reports/reports/asset-distribution.svg]]
